"""
Fit a StandardScaler on the regenerated summary-feature dataset.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

if __package__ is None or __package__ == "":
    import sys

    sys.path.append(str(Path(__file__).resolve().parent))
    from generate_feature_dataset import SUMMARY_COLUMNS  # type: ignore  # pylint: disable=import-error
else:
    from .generate_feature_dataset import SUMMARY_COLUMNS


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dataset",
        type=Path,
        required=True,
        help="CSV generated by scripts/generate_feature_dataset.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("models/features_v2"),
        help="Directory to store scaler artifacts.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    dataset = args.dataset.resolve()
    if not dataset.exists():
        raise FileNotFoundError(f"Dataset {dataset} not found.")

    df = pd.read_csv(dataset)
    missing = [col for col in SUMMARY_COLUMNS if col not in df.columns]
    if missing:
        raise ValueError(f"Dataset missing expected columns: {missing}")

    feature_columns = list(SUMMARY_COLUMNS)
    features = df[feature_columns].to_numpy(dtype=np.float32)
    scaler = StandardScaler().fit(features)

    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    scaler_path = output_dir / "feature_scaler.pkl"
    joblib.dump(scaler, scaler_path)

    json_path = output_dir / "feature_scaler.json"
    payload = {
        "mean": scaler.mean_.tolist(),
        "scale": scaler.scale_.tolist(),
        "var": scaler.var_.tolist(),
        "n_features": int(scaler.n_features_in_),
    }
    json_path.write_text(json.dumps(payload, indent=2))

    print(f"Saved scaler to {scaler_path}")
    print(f"Saved JSON parameters to {json_path}")


if __name__ == "__main__":
    main()
